# site.*
title: "Just Jason Green"
owner: "Jason Green"

# Build Settings
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            jumbotron_class: "underwater"
            title_separator: " @ "
exclude:
    - Dockerfile
    - Gemfile
    - Gemfile.lock
    - README.md
    - docker-compose.yml
    - vendor
gems:
    - jekyll-feed
    - jekyll-sitemap
sass:
    style: :compressed
