# site.*
title: "Just Jason Green"

# Build Settings
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            title_separator: " @ "
exclude:
    - Dockerfile
    - Gemfile
    - Gemfile.lock
    - README.md
    - docker-compose.yml
    - vendor
sass:
    style: :compressed
